### ISSUE TITLE
Allow sending other valid JSON types as IIPs

### ISSUE THREAD

**Issue by bergie** [flowbased/fbp#10]
Currently the FBP parser only allows strings to be defined as IIPs, but other types are also necessary.

Examples:

```fbp
1 -> IN SomeNode
true -> OPEN Gate
['foo', 'bar'] -> IN OtherNode
```

**Comment by tlrobinson** [comment]
Heads up I've implemented this (basically just pulled in peg.js' JSON grammar) in #58.
