### ISSUE TITLE
Allow anonymous nodes

### ISSUE THREAD

**Issue by jonnor** [flowbased/fbp#11]
It would be convenient sometimes to not have to specify a node identifier when instantiating components.
The typical example encountered in MicroFlo is converting between active=true convention (inside the program) and active=LOW (on the edges of the hardware because that is how the connected electronics works).

E.g.
`switch() OUT1 -> IN ia(InvertBoolean) OUT -> IN turnOn(DigitalWrite)`
would become:
`switch() OUT1-> IN (InvertBoolean) OUT -> IN turnOn(DigitalWrite)`

**Comment by tlrobinson** [comment]
I have implemented this in #58.
