### ISSUE TITLE
Invalid subgraphs input port names

### ISSUE THREAD

**Issue by djdeath** [flowbased/fbp#18]
I just spent 40 minutes trying to figure why my graph was not accepted by the FBP parser (telling me the START port doesn't exist).

It seems 'START' cannot be used as an input port of a sub graph, probably because of this : 
https://github.com/noflo/noflo/blob/master/src/components/Graph.coffee#L68

Maybe this kind of problem should be notified to the user more clearly with a message like 'Sorry $NAME is not a valid name for a port, please rename this port.'

**Comment by bergie** [comment]
The `START` port being disallowed is a NoFlo limitation, so fbp parser would be wrong place to do this
