### ISSUE TITLE
Cannot parse negative numbers

### ISSUE THREAD

**Issue by djdeath** [flowbased/fbp#20]
I might be wrong, but it seems the parser cannot deal with negative numbers : 

-1 -> BEGIN LastGraph(objects/SliceArray)

fails with : 

Fatal error: Expected " ", "#", "'", "EXPORT=", "INPORT=", "OUTPORT=", [A-Z.0-9_], [\n\r\u2028\u2029] or [a-zA-Z0-9_] but "-" found.

**Comment by jonnor** [comment]
Quotes are currently required.
