### ISSUE TITLE
Parser seems to need blanks around the arrows. 

### ISSUE THREAD

**Issue by jpaulm** [flowbased/fbp#21]
The parser seems to need blanks around the arrows. They should not be required.  Most languages do not require blanks next to special characters

**Comment by tlrobinson** [comment]
I have implemented this in #58.

**Comment by chadrik** [comment]
I would be very careful about this.  Right now the regex for component names is fairly restrictive, but I suspect that this project is still too new for everyone to have their say on this issue. Your change means that component names cannot use dashes in the future, and I have seen evidence in JavaFBP that people are using some fairly inclusive regular expressions for components and ports.

**Comment by chadrik** [comment]
Sorry, I meant to say dashes and angle brackets. 

Personally I don't care one way or the other, so if we can agree that one or both of these can never be used in a component or port name than I'm fine with this.

**Comment by jpaulm** [comment]
This is becoming a problem with the FBP free form notation: we seem to be getting more and more reserved symbols - JavaFBP doesn't have many restrictions as process and port names are surrounded with quotes, plus it can use the Java escape character convention.  In the FBP free form notation, IIRC, we (may) have to avoid square brackets, hyphen, angle brackets, comma, regular brackets, semi-colon, ...

Having to put blanks next to special characters is alien to users of most other programming languages - except COBOL, which I believe had the same conventions (probably because it allowed hyphens in names).

While the FBP free form notation that Wayne Stevens invented is very succinct, it may impose too many restrictions to be generally useful - besides, surely we want to start from diagrams, not text...?!

**Comment by jonnor** [comment]
Having some reserved characters does not impact significantly on the usefulness of the DSL.
Example: Java (or C,C++,JS etc) is not particularly less useful as a programming language because one cannot use `.:;,-{}{}` in variable names...

Note also that there is large overlap between the reserved characters the .fbp DSL have and these (ALGOL family) languages. This is good, because it makes it them not-that suprising to user familiar with such languages.

**Comment by jpaulm** [comment]
Actually, I guess hyphens in names are the main problem - if we simply
require that hyphens be replaced with underscores, as in most current
programming languages, a lot of these parsing problems go away!

**Comment by jpaulm** [comment]
Random comment: @jonnor @bergie do either of you know why we call the free form notation a DSL - I thought that meant "domain specific language"....
