### ISSUE TITLE
ENTER both splits lines and starts the display

### ISSUE THREAD

**Issue by jpaulm** [flowbased/fbp#22]
When using Visualize, ENTER both splits lines and starts the display, so you have to make sure the cursor is at the end of the network definition - this is really frustrating, as it is much more natural to make a change and then immediately hit ENTER!  It looks as though Visualize needs a Send button!

**Comment by jonnor** [comment]
Visualize is no longer part of this repo, closing. We may instead bring textual editing to Flowhub at some point.
