### ISSUE TITLE
Visualize lowercases port names 

### ISSUE THREAD

**Issue by jpaulm** [flowbased/fbp#24]
Visualize lowercases port names. However I had understood from @bergie (maybe I misunderstood) that NoFlo only lowercases port names in generated JSON. I guess it doesn't matter much, as I believe that port names are case-insensitive, but it would be nice to see on the diagram what you actually typed in (same applies to array notation)!

**Comment by jonnor** [comment]
Duplicate of #30 , which has now been fixed. See #30 and #51 for details.
