### ISSUE TITLE
Would like to have a title within the file

### ISSUE THREAD

**Issue by jpaulm** [flowbased/fbp#27]
I have some (old) NoFlo JSON which has something called "name" within "properties".  I guess this can be obtained from the file name, but tools like Visualize accept input from a panel or textarea, so it would be nice to have a convention for specifying the file name, right in the network definition.

In the pre-NoFlo .fbp notation, we could specify `xxx:` at the beginning of the network, and also use the same convention for subnets, which could be included within the same file, if desired, separated by semi-colons.

Comments, @bergie @jonnor @forresto ?

**Comment by bergie** [comment]
In NoFlo we support providing the graph name via an annotation:

```fbp
# @name SomeGraph
```

By default NoFlo uses the filename as the graph name, but this is useful for [aliasing graphs](https://noflojs.org/documentation/publishing/#aliasing-components), for instance when you have multiple implementation of the same graph for different runtime environments (like noflo-browser and noflo-nodejs).

Would make sense implementing the same time we do #33
