### ISSUE TITLE
syntax for grouping

### ISSUE THREAD

**Issue by ensonic** [flowbased/fbp#29]
When I do:

```
# In the graph we first need to define the nodes and the connections between them
```

   Read(filesystem/ReadFile) OUT -> IN Parse(strings/ParseJson) OUT -> IN  Extract1(objects/ExtractProperty) OUT -> IN Display(core/Output)

```
# Configure Extract
'dependencies' -> KEY Extract1
'noflo' -> KEY Extract1

# Start off the graph by sending a filename to the file reader
'package.json' -> IN Read
```

I get:

```
DATA -> KEY Extract1() CONN
DATA -> KEY Extract1() DATA
DATA -> KEY Extract1() DISC
DATA -> KEY Extract1() CONN
DATA -> KEY Extract1() DATA
DATA -> KEY Extract1() DISC
```

what I want is

```
DATA -> KEY Extract1() CONN
DATA -> KEY Extract1() DATA
DATA -> KEY Extract1() DATA
DATA -> KEY Extract1() DISC
```

Is there a syntax for it already? According to the tests there is not.

**Comment by bergie** [comment]
Not really in scope of the FBP syntax, this is related to NoFlo event handling. And there we've mostly deprecated the connect/disconnect stuff anyway.
