### ISSUE TITLE
fbp lowercases port names

### ISSUE THREAD

**Issue by davidmaxwaterman** [flowbased/fbp#30]
This causes a problem when using them as graphs since the-graph (somewhere) then duplicates the ports, with the duplicate being named in uppercase.

Please consider maintaining the case of the port names, or changing noflo.graph.loadFBP() to convert them back to uppercase.

**Comment by forresto** [comment]
I don't have an opinion on this one (other than wanting to break backwards compatibility and respect mixed case...).

**Comment by davidmaxwaterman** [comment]
This has caused another problem. It's a real pig...it seems like we have to manually uppercase them, and have to make a nofloGraph rather than a graph since if we assign to the graph with an object of type 'graph', it tries to use loadJSON() which lowercases them again....grrr.

**Comment by jonnor** [comment]
Fixed in #51, one ca now opt-out to normalize-to-lowercase behavior - both when using the API and when using the commandline tool.
