### ISSUE TITLE
No error on refering non-existing process in inport declaration

### ISSUE THREAD

**Issue by jonnor** [flowbased/fbp#78]
Example:
```
INPORT=noexist.IN:broken
INPORT=exist.IN:works

exist(foo/Bar)
```
Expected: Error with message explaining that `noexist` referenced in inport `broken` does not exist

**Comment by bergie** [comment]
The FBP parser can't know this. Should be handled by the runtime that you're targeting

**Comment by jonnor** [comment]
Why can it not? All the process names are decided by the FBP parser. So if there is a reference to a process which does not exist in exported ports, surely that can be detected?
If it was about port names I would follow, since that requires component definition, which the parser does not have.

**Comment by bergie** [comment]
Ah, sorry, misread you (though you meant non-existing port). You're right. It should error on this
